microsoft/win-net-test

- src/fnmp.props
- src/sys/fnio/filter.c
Only check whether the masked packet bits match the masked pattern bits in the TX filtering routine.
> Improve TX filtering API

- .azure/OneBranch.Official.yml
- .azure/OneBranch.PullRequest.yml
Internal build was failing because of missing nuget package dependencies.
> Restore Nuget Packages in OneBranch Builds

- .azure/OneBranch.Official.yml
- .azure/OneBranch.PullRequest.yml
- test/functional/fnmpfunctionaltests.vcxproj
Fixes two problems:
1. Link error from `fnmpfunctionaltests` - by changing it to a static lib (hack) to not link anything
2. arm64x build error for drvlib - Disable this (in the undocked repo) and update the submodule dependency
> Fix OneBranch Builds

- fnmp.sln
- test/debugcrt/debugcrt.vcxproj
- test/functional/fnmpfunctionaltests.vcxproj
- tools/functional.ps1
- Fix script error.
- Copy debug CRT binaries to output directory on debug builds, so test machines without VS installed can load their CRT.
Resolves #26
> Fix functional tests - script error and local debug execution

- src/lib/fnmpapi.vcxproj
- src/sys/inf/fnmp.inx
- src/sys/nt/fnmp.vcxproj
- version.json
Consumers of FNMP don't know where to load fnmpapi.dll, so toss it into system32.
> Binplace FNMPAPI.dll into system32

- inc/fnlwfapi.h
- inc/fnlwfapi_dyn.h
- inc/fnmpapi.h
- inc/fnmpapi_dyn.h
- test/functional/fnfunctionaltests.vcxproj
- test/functional/tests.cpp
Add header helpers to easily consume the FNMP and FNLWF APIs using runtime dynamic linking.
Addresses #34
> Add runtime dynamic linking API helpers

- test/functional/lib/tests.cpp
Fix bug caught by OB arm64 build
```
test\functional\lib\tests.cpp(318,16): Error C4296: '>': expression is always false
```
> Fix bug caught by OB arm64 build

- inc/fnioctl_km.h
- inc/fnioctl_um.h
- inc/fniotypes.h
Two minor cleanups to the user-facing headers to hopefully push the mirror CI pipeline through
- Align on HANDLE as the underlying type for FNIOCTL_HANDLE
- Don't wrap included headers in extern "C"
> Minor header cleanup

- .azure/OneBranch.Official.yml
- .azure/OneBranch.PullRequest.yml
- .github/workflows/ci.yml
- src/nuget.config
- tools/build.ps1
This file is not necessary to restore nuget packages. Additionally, we're getting an s360 for these files in OneBranch. Let's make it go away.
> Remove Nuget Config

- README.md
- docs/wskclient.md
- inc/fnsock.h
- inc/wskclient.h
- src/sock/km/sock.c
- src/sock/um/sock.c
- src/wskclient/wskclient.c
- src/wskclient/wskclient.vcxproj
- test/functional/bin/km/fnfunctionaltestdrv.vcxproj
- test/functional/lib/tests.cpp
- wnt.sln
Leverage the wskclient library from the OS tests to implement kernel mode fnsock instead of adding another WSK wrapper. Also, expose wskclient as another tool in the win-net-test tool bag. When we get time we can replace the OS version of wskclient with this version.
> Use and expose wskclient library

- src/lwf/sys/rx.c
- version.json
NDIS requires LWFs return any NBLs they held on to before completing a pause request, so acquire a rundown reference before filtering.
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ndis/nc-ndis-filter_pause
Also bump the version to 0.4.3 for a bugfix release.
> acquire LWF rundown before filtering NBLs

- inc/fnsock.h
- src/sock/km/fnsock_km.def
- src/sock/km/fnsock_km.vcxproj
- src/sock/km/sock.c
- src/sock/um/fnsock_um.vcxproj
- src/sock/um/sock.c
- test/functional/bin/km/fnfunctionaltestdrv.vcxproj
- tools/functional.ps1
- tools/prepare-machine.ps1
- tools/setup.ps1
- tools/sign.ps1
Expose FnSock as dll/sys libraries. This makes consumption more flexible compared to static libs (which brings in complexities such as libs compiled with different CRTs). The next step will be to package the headers and import libs into a nuget package that other projects can consume.
> Expose FnSock as dll/sys

- inc/fniotypes.h
- inc/fnmpapi.h
- inc/fnmpioctl.h
- src/mp/sys/miniport.c
- src/mp/sys/miniport.h
- src/mp/sys/shared.c
- version.json
XDP needs a way to configure arbitrary task offload capabilities; not merely toggle them on and off.
Add a new, extensible options struct to a new API and thunk the old API.
> add offload options to task offload API

- tools/nuget/win-net-test.props
Most .props files automatically add includes to the include path, so do that. Don't add libraries, since many projects won't need to link the libraries, and we have both user and kernel mode variants.
> automatically include includes in nuget props

- inc/fniotypes.h
- inc/fnlwfapi.h
- inc/fnmpapi.h
- inc/fnsock.h
- inc/pkthlp.h
- src/common/inc/fnassert.h
- src/common/inc/fnrtl.h
- test/cxplat/inc/cxplat.h
- test/functional/lib/tests.cpp
- test/functional/testframeworkapi.h
_KERNEL_MODE is set by default by msbuild when compiling KM drivers. No need to rely on KERNEL_MODE which is set in windows.undocked.props (undocked submodule).
After cleaning this up, we can get rid of KERNEL_MODE flag in XDP as well.
> Use _KERNEL_MODE instead

- inc/fnmpapi.h
> fix const correctness of offload options

- src/common/lib/fnio/enqueue.c
- src/mp/sys/rx.c
We're leaking NBLs in enqueue failure paths and the FNMP low resources RX path.
> fix a few NBL leaks

- inc/fnmpapi.h
- inc/fnmpioctl.h
- src/mp/sys/shared.c
I realized #87 is not seamlessly extensible if we add more fields to the options structs; we should not require apps be recompiled to use newer versions of the FNMPAPI.
add an implicit size field to the IOCTL.
> FNMP: make offload options extensible

- inc/fniotypes.h
- inc/fnlwfapi.h
- inc/fnlwfioctl.h
- inc/fnmpapi.h
- inc/fnmpioctl.h
- inc/fnoid.h
- src/common/inc/bounce.h
- src/common/lib/bounce/bounce.c
- src/lwf/sys/default.c
- src/lwf/sys/dispatch.c
- src/lwf/sys/dispatch.h
- src/lwf/sys/oid.c
- src/lwf/sys/oid.h
- src/lwf/sys/precomp.h
- src/mp/sys/dispatch.c
- src/mp/sys/dispatch.h
- src/mp/sys/exclusive.c
- src/mp/sys/miniport.h
- src/mp/sys/oid.c
- src/mp/sys/oid.h
- src/mp/sys/precomp.h
- test/functional/lib/tests.cpp
OIDs can be sent to specific NDIS ports, which are used, among other things, for setting RSS on a VF via the synthetic virtual NIC above it. Add support for filtering on ports, which was relatively straightforward.
Unfortunately, we failed to make the OID_KEY struct easily extensible: it was encompassed as a field in other structs, so a fair amount of boilerplate had to be rewritten. Future extensions should be as straightforward as originally intended.
> Add support for filtering OIDs by port numbers

- src/mp/sys/miniport.c
- src/mp/sys/oid.c
- test/functional/lib/tests.cpp
NDIS intercepts OIDs to non-default ports by default, which breaks our use case for port-specific OID handling.
Also stub support for RSS-related OIDs that are typically handled by NDIS.
> do not intercept OIDs to non-default port

- src/mp/sys/oid.c
> comment to avoid adding new static dummy OIDs on behalf of tests

- .github/workflows/ci.yml
- tools/create-nuget-package.ps1
- tools/nuget/win-net-test.nuspec.in
- tools/nuget/win-net-test.props
- version.json
The common practice, and most convenient design, for developer nugets include all architectures.
> include all architectures in dev nuget

- src/common/inc/fnrtl.h
- src/common/lib/bounce/bounce.vcxproj
- src/lwf/sys/fnlwf.vcxproj
- src/mp/sys/fnmp.vcxproj
The `RtlCopyVolatileMemory` is defined in the newest WDK, which GitHub implicitly started using.
> get newest wdk working

- .github/dependabot.yml
Ensure our nuget dependencies are kept up-to-date with dependabot.
> make dependabot update our nuget dependencies

- .github/workflows/ci.yml
- src/common/lib/bounce/bounce.vcxproj
- src/common/lib/fnio/fnio.vcxproj
- src/isr/svc/isrsvc.vcxproj
- src/isr/sys/isrdrv.vcxproj
- src/lwf/sys/fnlwf.vcxproj
- src/lwf/sys/inf/fnlwf.inx
- src/mp/sys/fnmp.vcxproj
- src/mp/sys/inf/fnmp.inx
- src/mp/sys/packages.config
- src/nuget.config
- src/sock/km/fnsock_km.vcxproj
- src/sock/um/fnsock_um.vcxproj
- src/wnt.cpp.kernel.props
- src/wnt.cpp.props
- src/wskclient/wskclient.vcxproj
- test/cxplat/lib/km/cxplat_km.vcxproj
- test/cxplat/lib/um/cxplat_um.vcxproj
- test/functional/bin/fnfunctionaltests.vcxproj
- test/functional/bin/km/fnfunctionaltestdrv.vcxproj
- test/functional/lib/fnfunctionaltestlib_km.vcxproj
- test/functional/lib/fnfunctionaltestlib_um.vcxproj
- test/pkthlp/km/pkthlp_km.vcxproj
- test/pkthlp/um/pkthlp_um.vcxproj
- tools/build.ps1
Instead of relying on the WDK and SDK provided by the build machines, take a specific dependency using nuget packages. 
Fix a few build breaks caused by the new WDK.
Also remove building on WS2019, which is causing headaches and is obsolete as a build env. WS2019 is still used for testing.
> Build using latest WDK and SDK via nuget

- src/lwf/sys/fnlwf.vcxproj
- src/mp/sys/fnmp.vcxproj
Allow nuget to parse the vcxproj files before the LatestWdkPlatformVersion variable is set, which is needed to initially restore nuget packages.
Without this, the parsing fails, trying to compare a numerical value with an empty string.
> Fix comparison when wdk version is not set

- docs/release.md
Document the release process based on the step followed for the 1.3.0 release.
> Add release process documentation
